name: build

on:
  push:
    branches: [ "master", "develop" ]
    tags:
    - 'v*'
  pull_request:
    branches: [ "master", "develop" ]

jobs:
  # new release upon tagging
  create-release:
    runs-on: ubuntu-latest
    permissions: write-all
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}

  # Handleiding PDF
  build-pdf:
    runs-on: ubuntu-latest
    permissions: write-all
    container:
      image: ghcr.io/ifilot/lualatex-debian12:v0.6.0

    steps:
    - uses: actions/checkout@v3
    - name: Install additional dependencies
      run: |
        sudo apt-get install poppler-utils
    - name: Build PDF
      run: |
        latexmk -pdflatex=lualatex -f -pdf -jobname="p2000t-sdkaart-handleiding-inner" main.tex
        pdfseparate cover/cover.pdf cover-page%d.pdf
        pdfunit cover-page1.pdf p2000t-sdkaart-handleiding-inner.pdf cover-page2.pdf p2000t-sdkaart-handleiding.pdf
    - name: Upload launcher
      uses: actions/upload-artifact@v3
      with:
        name: p2000t-sdkaart-handleiding.pdf
        path: p2000t-sdkaart-handleiding.pdf